// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbQsJ1_tk6hULwij92uDoFFspaDDnU27E',
    appId: '1:126180439090:web:7f25c90f199455830af82b',
    messagingSenderId: '126180439090',
    projectId: 'proswing-backend',
    authDomain: 'proswing-backend.firebaseapp.com',
    storageBucket: 'proswing-backend.appspot.com',
    measurementId: 'G-VNZVE8L8EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4oLo6TR0wNXd3o62_Yeg7eJipqQvLKY',
    appId: '1:126180439090:android:912e12ee37e869fc0af82b',
    messagingSenderId: '126180439090',
    projectId: 'proswing-backend',
    storageBucket: 'proswing-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZU6d9j4ivtkiwB-rVPEFckdrxSOjSr-s',
    appId: '1:126180439090:ios:c7e17fa3e3ca0e690af82b',
    messagingSenderId: '126180439090',
    projectId: 'proswing-backend',
    storageBucket: 'proswing-backend.appspot.com',
    iosClientId: '126180439090-nqk8gt3o91n6v17r9b5a8bk3qn0018aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.proswing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZU6d9j4ivtkiwB-rVPEFckdrxSOjSr-s',
    appId: '1:126180439090:ios:c7e17fa3e3ca0e690af82b',
    messagingSenderId: '126180439090',
    projectId: 'proswing-backend',
    storageBucket: 'proswing-backend.appspot.com',
    iosClientId: '126180439090-nqk8gt3o91n6v17r9b5a8bk3qn0018aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.proswing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbQsJ1_tk6hULwij92uDoFFspaDDnU27E',
    appId: '1:126180439090:web:e4850814da46ce460af82b',
    messagingSenderId: '126180439090',
    projectId: 'proswing-backend',
    authDomain: 'proswing-backend.firebaseapp.com',
    storageBucket: 'proswing-backend.appspot.com',
    measurementId: 'G-73JY11ZFLR',
  );
}
